name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install and configure Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          amplify configure

      - name: Initialize Amplify app
        run: |
          amplify pull --appId d2ryjycfsf8d0i --envName dev

      - name: Build and deploy to Amplify
        run: |
          npm run build
          amplify publish
